import { predictStore } from "../state/predictStore.js";
import { formatRiskFactorsForUI } from "./riskFactorDisplay.js";

/**
 * Generate and download PDF medical report from latest prediction.
 * @param {import('../domain/riskEngine.js').RiskResult} result
 */
export async function downloadMedicalReport(result) {
  const { jsPDF } = window.jspdf ?? {};
  if (!jsPDF) {
    alert("PDF library not loaded. Check your network connection and reload.");
    return;
  }

  const wizard = predictStore.getState().wizard;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const margin = 16;
  let y = margin;

  const primary = [37, 99, 235];
  const danger = [239, 68, 68];
  const success = [34, 197, 94];

  doc.setFillColor(...primary);
  doc.rect(0, 0, W, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("CardioFL — Medical Risk Assessment Report", margin, 14);
  doc.setFontSize(9);
  doc.text("Federated Learning · Privacy-Preserving Healthcare Intelligence", margin, 21);

  y = 36;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 10;

  sectionTitle(doc, "Patient summary", margin, y);
  y += 8;
  const basic = wizard?.basic ?? {};
  const rows = [
    ["Age", String(basic.age ?? "—")],
    ["Gender", String(basic.gender ?? "—")],
    ["BMI", String(basic.bmi ?? "—")],
    ["Family history (heart disease)", basic.family_history_heart_disease ? "Yes" : "No"],
  ];
  y = tableRows(doc, rows, margin, y) + 6;

  sectionTitle(doc, "Prediction outcome", margin, y);
  y += 8;
  const riskColor = result.label === "HIGH" ? danger : success;
  doc.setTextColor(...riskColor);
  doc.setFontSize(14);
  doc.text(`Risk level: ${result.label}`, margin, y);
  y += 8;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.text(`Risk score: ${result.risk_pct.toFixed(1)}%`, margin, y);
  y += 6;
  const conf = result.confidence != null ? `${Math.round(result.confidence * 100)}%` : "—";
  doc.text(`Model confidence: ${conf}`, margin, y);
  y += 6;
  doc.text(`Decision threshold: ${(result.threshold * 100).toFixed(0)}%`, margin, y);
  y += 10;

  sectionTitle(doc, "Clinical interpretation", margin, y);
  y += 7;
  doc.setFontSize(10);
  const msg = doc.splitTextToSize(result.message ?? "", W - margin * 2);
  doc.text(msg, margin, y);
  y += msg.length * 5 + 6;

  sectionTitle(doc, "Risk factor contributions", margin, y);
  y += 8;
  const factors = formatRiskFactorsForUI(result.factor_contributions);
  for (const f of factors) {
    if (y > 260) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(`${f.name}: ${f.signed}`, margin, y);
    const barW = (W - margin * 2) * (f.impact_pct / 100);
    if (f.tier === "critical") doc.setFillColor(239, 68, 68);
    else if (f.tier === "healthy") doc.setFillColor(34, 197, 94);
    else doc.setFillColor(59, 130, 246);
    doc.rect(margin, y + 2, barW, 3, "F");
    y += 10;
  }
  y += 4;

  if (result.recommendations) {
    sectionTitle(doc, "Recommendations", margin, y);
    y += 8;
    doc.setFontSize(10);
    for (const item of result.recommendations.immediate ?? []) {
      if (y > 270) { doc.addPage(); y = margin; }
      doc.text(`• ${item}`, margin + 2, y);
      y += 6;
    }
    y += 4;
    for (const item of result.recommendations.lifestyle ?? []) {
      if (y > 270) { doc.addPage(); y = margin; }
      doc.text(`• ${item}`, margin + 2, y);
      y += 6;
    }
  }

  y = Math.max(y + 8, 250);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, W - margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const note =
    "This report was generated by CardioFL using federated learning. Raw patient records remain at participating hospitals; only aggregated model updates are shared. This document is for informational purposes and does not replace professional medical advice.";
  doc.text(doc.splitTextToSize(note, W - margin * 2), margin, y);

  const filename = `CardioFL_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

function sectionTitle(doc, text, x, y) {
  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.text(text, x, y);
}

function tableRows(doc, rows, x, startY) {
  let y = startY;
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  for (const [k, v] of rows) {
    doc.text(`${k}:`, x, y);
    doc.text(v, x + 52, y);
    y += 6;
  }
  return y;
}
